// frontend-react/src/App.tsx
import { useState, useEffect, useRef } from 'react';
import { Canvas } from '@react-three/fiber';
import { Mic, Square } from 'lucide-react';
import { useAudioRecorder } from './hooks/useAudioRecorder';
import { TechNodeSphere } from './components/TechNodeSphere';
import './index.css';

interface ChatMessage {
  role: 'user' | 'ai';
  text: string;
  timestamp: string;
}

function App() {
  const { isRecording, volumeLevel, startSpeechRecognition, stopRecording, speak } = useAudioRecorder();
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [status, setStatus] = useState('Ready');
  const chatBoxRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (chatBoxRef.current) {
      chatBoxRef.current.scrollTop = chatBoxRef.current.scrollHeight;
    }
  }, [chatMessages]);

  const handleToggleRecording = async () => {
    if (!isRecording) {
      setStatus('Listening...');
      try {
        const transcript = await startSpeechRecognition();
        
        setStatus('Ready');
        if (transcript) {
          processMessage(transcript);
        }
      } catch (err) {
        setStatus('Error - try again');
      }
    } else {
      stopRecording();
      setStatus('Ready');
    }
  };

  const processMessage = (transcript: string) => {
    const newUserMsg: ChatMessage = {
      role: 'user',
      text: transcript,
      timestamp: new Date().toLocaleTimeString(),
    };
    
    setChatMessages((prev) => [...prev, newUserMsg]);

    const responses = [
      'That sounds great!',
      'I hear you!',
      'Interesting, tell me more.',
      'Got it!',
      'Nice!',
      'Understood!',
      'Processing your request...'
    ];
    const reply = responses[Math.floor(Math.random() * responses.length)];

    const newAiMsg: ChatMessage = {
      role: 'ai',
      text: reply,
      timestamp: new Date().toLocaleTimeString(),
    };

    setChatMessages((prev) => [...prev, newAiMsg]);
    speak(reply);
  };

  const clearChat = () => {
    setChatMessages([]);
    setStatus('Ready');
  };

  return (
    <>
      <div className="canvas-container">
        <Canvas camera={{ position: [0, 0, 5], fov: 60 }}>
          <TechNodeSphere volumeLevel={volumeLevel} />
        </Canvas>
      </div>

      <div className="ui-overlay">
        <div className="header">
          <h1>Voice AI</h1>
          <span className={`status-badge ${isRecording ? 'recording' : ''}`}>
            {status}
          </span>
        </div>

        <div className="main-content">
          <div className="chat-box" ref={chatBoxRef}>
            {chatMessages.length === 0 ? (
              <div className="empty-state">Press the mic and start talking.</div>
            ) : (
              chatMessages.map((msg, idx) => (
                <div key={idx} className={`message ${msg.role}`}>
                  <div className="bubble">{msg.text}</div>
                  <span className="timestamp">{msg.timestamp}</span>
                </div>
              ))
            )}
          </div>
        </div>

        {isRecording && volumeLevel > 0 && (
          <div className="transcript-indicator">
            Listening...
          </div>
        )}

        <div className="controls-wrapper">
          <div className="controls">
            <button className="btn-clear" onClick={clearChat}>
              Clear
            </button>
            
            <button 
              className={`btn-mic ${isRecording ? 'recording' : ''}`}
              onClick={handleToggleRecording}
              title={isRecording ? 'Stop Recording' : 'Start Recording'}
            >
              {isRecording ? <Square size={24} /> : <Mic size={24} />}
            </button>
          </div>
        </div>
      </div>
    </>
  );
}

export default App;

// frontend/src/app/app.component.ts
import { Component, ViewChild, ElementRef, NgZone } from '@angular/core';
import { CommonModule } from '@angular/common';
import { AudioService } from './audio.service';

interface ChatMessage {
  role: 'user' | 'ai';
  text: string;
  timestamp: string;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @ViewChild('chatBox') chatBox!: ElementRef<HTMLDivElement>;

  isRecording = false;
  status = 'Ready';
  currentTranscript = '';
  chatMessages: ChatMessage[] = [];
  private transcriptSubscription: any;

  constructor(
    private audioService: AudioService,
    private ngZone: NgZone
  ) {}

  toggleRecording() {
    if (!this.isRecording) {
      this.status = 'Listening...';
      this.isRecording = true;
      this.currentTranscript = '';

      const transcript$ = this.audioService.startSpeechRecognition();

      this.transcriptSubscription = transcript$.subscribe({
        next: (text) => {
          this.ngZone.run(() => {
            if (text) {
              this.currentTranscript = text;
            }
          });
        },
        complete: () => {
          this.ngZone.run(() => {
            this.isRecording = false;
            this.status = 'Ready';
            if (this.currentTranscript) {
              this.processMessage(this.currentTranscript);
            }
          });
        },
        error: () => {
          this.ngZone.run(() => {
            this.isRecording = false;
            this.status = 'Error - try again';
          });
        }
      });
    } else {
      this.audioService.stopRecording();
      this.isRecording = false;
    }
  }

  private processMessage(transcript: string) {
    this.chatMessages.push({
      role: 'user',
      text: transcript,
      timestamp: new Date().toLocaleTimeString()
    });
    this.scrollToBottom();

    const responses = [
      'That sounds great!',
      'I hear you!',
      'Interesting, tell me more.',
      'Got it!',
      'Nice!',
      'Understood!'
    ];
    const reply = responses[Math.floor(Math.random() * responses.length)];

    this.chatMessages.push({
      role: 'ai',
      text: reply,
      timestamp: new Date().toLocaleTimeString()
    });
    this.audioService.speak(reply);
    this.scrollToBottom();
  }

  private scrollToBottom() {
    setTimeout(() => {
      const chatBox = this.chatBox?.nativeElement;
      if (chatBox) {
        chatBox.scrollTop = chatBox.scrollHeight;
      }
    }, 100);
  }

  clearChat() {
    this.chatMessages = [];
    this.status = 'Ready';
  }
}

<div class="page">
  <div class="card">
    <div class="card-header">
      <h1>Voice Assistant</h1>
      <span class="status">{{ status }}</span>
    </div>

    <div class="chat-box" #chatBox>
      <div *ngFor="let msg of chatMessages" class="message" [ngClass]="msg.role">
        <div class="bubble">
          <p>{{ msg.text }}</p>
          <span class="timestamp">{{ msg.timestamp }}</span>
        </div>
      </div>

      <div *ngIf="chatMessages.length === 0" class="empty">
        Press the mic and start talking.
      </div>
    </div>

    <div class="transcript" *ngIf="currentTranscript && isRecording">
      {{ currentTranscript }}
    </div>

    <div class="controls">
      <button class="btn-clear" (click)="clearChat()">Clear</button>
      <button class="btn-mic" [ngClass]="{ recording: isRecording }" (click)="toggleRecording()">
        {{ isRecording ? 'Stop' : 'Talk' }}
      </button>
    </div>
  </div>
</div>
