// frontend-react/src/pages/Dashboard.tsx
import { useEffect, useMemo, memo, useCallback } from 'react';
import { useDashboard } from '../hooks/useDashboard';
import '../styles/dashboard.css';

const LoadingSpinner = memo(() => <div className="spinner"></div>);
const SmallSpinner = memo(() => <div className="spinner small"></div>);

const TableRow = memo(({ row, pkColumn, columns, onEdit, onDelete }: any) => (
  <tr key={pkColumn ? row[pkColumn] : Math.random()}>
    {Object.keys(row).map((key) => (
      <td key={key}>
        <div className="cell">{row[key]}</div>
      </td>
    ))}
    <td className="row-actions">
      <button className="btn-edit" onClick={() => onEdit(row)}>
        Edit
      </button>
      <button className="btn-delete" onClick={() => onDelete(row)}>
        Delete
      </button>
    </td>
  </tr>
));

function Dashboard() {
  const dashboard = useDashboard();

  useEffect(() => {
    dashboard.loadTables();
  }, [dashboard.loadTables]);

  return (
    <div className="dashboard">
      {/* Sidebar */}
      <aside className="sidebar">
        <h2>Tables</h2>
        {dashboard.isLoadingTables ? (
          <div className="loading-overlay">
            <LoadingSpinner />
          </div>
        ) : (
          dashboard.tables.map((table) => (
            <button
              key={table}
              className={`table-btn ${table === dashboard.selectedTable ? 'active' : ''}`}
              onClick={() => dashboard.selectTable(table)}
            >
              {table}
            </button>
          ))
        )}
      </aside>

      {/* Main Content */}
      <main className="content">
        {dashboard.errorMessage && (
          <div className="error">{dashboard.errorMessage}</div>
        )}

        {!dashboard.selectedTable && (
          <div className="empty">Select a table to view and insert data.</div>
        )}

        {dashboard.selectedTable && (
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '16px' }}>
              <h2 style={{ margin: 0 }}>{dashboard.selectedTable}</h2>
              <button type="button" className="btn-refresh" onClick={() => dashboard.refreshTable()}>
                Refresh
              </button>
            </div>

            {/* Insert/Edit Form */}
            <form
              className={`insert-form ${dashboard.isLoadingColumns || dashboard.isSubmitting ? 'loading' : ''}`}
              onSubmit={(e) => {
                e.preventDefault();
                dashboard.submit();
              }}
            >
              {dashboard.isLoadingColumns ? (
                <div className="form-loading">
                  <LoadingSpinner />
                  <span>Loading fields...</span>
                </div>
              ) : (
                <>
                  {dashboard.columns.map((col) => {
                    if (!dashboard.shouldShowInForm(col, dashboard.editingPkValue !== null)) {
                      return null;
                    }

                    const isAutoGen = dashboard.isAutoGenerated(col);
                    const isEditing = dashboard.editingPkValue !== null;

                    return (
                      <div
                        key={col.name}
                        className={`field ${isAutoGen && !isEditing ? 'auto-gen' : ''}`}
                      >
                        <label>
                          {col.name}
                          <span className="type">{col.type}</span>
                          {dashboard.getColumnHint(col) && (
                            <span className="hint">{dashboard.getColumnHint(col)}</span>
                          )}
                          {col.primary_key && <span className="pk">PK</span>}
                        </label>

                        {dashboard.isJsonb(col) ? (
                          <div className="jsonb-input-group">
                            <input
                              type="text"
                              value={
                                (dashboard.formData[col.name] || '').substring(0, 50) +
                                (dashboard.formData[col.name]?.length > 50 ? '...' : '')
                              }
                              readOnly
                              placeholder={dashboard.getJsonbPlaceholder(col)}
                              className="jsonb-preview"
                            />
                            <button
                              type="button"
                              className="btn-edit-json"
                              onClick={() => dashboard.openJsonEditor(col.name)}
                              title="Edit JSON"
                            >
                              ✎
                            </button>
                          </div>
                        ) : dashboard.isTimestamp(col) ? (
                          <input
                            type="datetime-local"
                            value={dashboard.formData[col.name] || ''}
                            onChange={(e) => dashboard.updateField(col.name, e.target.value)}
                            disabled={isEditing && col.primary_key}
                            readOnly={isAutoGen && !isEditing}
                            name={col.name}
                          />
                        ) : (
                          <input
                            type="text"
                            value={dashboard.formData[col.name] || ''}
                            onChange={(e) => dashboard.updateField(col.name, e.target.value)}
                            disabled={isEditing && col.primary_key}
                            readOnly={isAutoGen && !isEditing}
                            name={col.name}
                            placeholder={isAutoGen ? 'Auto-generated' : ''}
                          />
                        )}
                      </div>
                    );
                  })}

                  <button type="submit" className="btn-insert" disabled={dashboard.isLoadingColumns || dashboard.isSubmitting}>
                    {dashboard.isSubmitting ? (
                      <>
                        <SmallSpinner />
                        {dashboard.editingPkValue !== null ? 'Saving...' : 'Inserting...'}
                      </>
                    ) : (
                      <>{dashboard.editingPkValue !== null ? 'Save Changes' : 'Insert Row'}</>
                    )}
                  </button>

                  {dashboard.editingPkValue !== null && (
                    <button type="button" className="btn-cancel" onClick={() => dashboard.cancelEdit()}>
                      Cancel
                    </button>
                  )}
                </>
              )}
            </form>

            {/* JSON Editor Modal */}
            {dashboard.jsonEditorOpen && (
              <div className="modal-overlay" onClick={() => dashboard.closeJsonEditor()}>
                <div className="modal-content" onClick={(e) => e.stopPropagation()}>
                  <div className="modal-header">
                    <h3>Edit {dashboard.jsonEditorField}</h3>
                    <button type="button" className="btn-close" onClick={() => dashboard.closeJsonEditor()}>
                      ✕
                    </button>
                  </div>
                  <textarea
                    className="json-editor"
                    value={dashboard.jsonEditorValueRef.current}
                    onChange={(e) => {
                      dashboard.jsonEditorValueRef.current = e.target.value;
                    }}
                    placeholder='{"key": "value"}'
                  />
                  <div className="modal-footer">
                    <button type="button" className="btn-cancel" onClick={() => dashboard.closeJsonEditor()}>
                      Cancel
                    </button>
                    <button type="button" className="btn-save-json" onClick={() => dashboard.saveJsonEditor()}>
                      Save
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* Rows Table */}
            {dashboard.isLoadingRows ? (
              <div className="table-scroll">
                <table className="rows-table">
                  <thead>
                    <tr>
                      {dashboard.columns.map((col) => (
                        <th key={col.name}>{col.name}</th>
                      ))}
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {[0, 1, 2, 3, 4, 5].map((i) => (
                      <tr key={i} className="skeleton-row">
                        {dashboard.columns.map((col) => (
                          <td key={col.name}>
                            <div className="skeleton-cell"></div>
                          </td>
                        ))}
                        <td>
                          <div className="skeleton-actions"></div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ) : dashboard.rows.length > 0 ? (
              <div className="table-scroll">
                <table className="rows-table">
                  <thead>
                    <tr>
                      {Object.keys(dashboard.rows[0]).map((key) => (
                        <th key={key}>{key}</th>
                      ))}
                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {dashboard.rows.map((row, idx) => (
                      <TableRow
                        key={dashboard.pkColumn ? row[dashboard.pkColumn] : idx}
                        row={row}
                        pkColumn={dashboard.pkColumn}
                        columns={dashboard.columns}
                        onEdit={dashboard.startEdit}
                        onDelete={dashboard.deleteRow}
                      />
                    ))}
                  </tbody>
                </table>
              </div>
            ) : (
              <div className="empty">No rows yet.</div>
            )}
          </div>
        )}
      </main>
    </div>
  );
}

export default memo(Dashboard);

// frontend/src/app/dashboard/dashboard.component.ts
import { Component, computed, inject, signal, OnInit } from '@angular/core';
import { AdminService, ColumnInfo } from '../admin.service';

@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  private readonly adminService = inject(AdminService);

  protected readonly tables = signal<string[]>([]);
  protected readonly selectedTable = signal<string>('');
  protected readonly columns = signal<ColumnInfo[]>([]);
  protected readonly rows = signal<any[]>([]);
  protected readonly formData = signal<Record<string, string>>({});
  protected readonly errorMessage = signal<string>('');
  protected readonly editingPkValue = signal<string | null>(null);

  protected readonly isLoadingTables = signal(false);
  protected readonly isLoadingColumns = signal(false);
  protected readonly isLoadingRows = signal(false);
  protected readonly isSubmitting = signal(false);

  protected readonly jsonEditorOpen = signal(false);
  protected readonly jsonEditorField = signal('');
  protected jsonEditorValue = '';

  protected readonly pkColumn = computed(() => this.columns().find((c) => c.primary_key)?.name);

  ngOnInit() {
    this.loadTables();
  }

  private loadTables() {
    this.isLoadingTables.set(true);
    this.adminService.getTables().subscribe({
      next: (res) => this.tables.set(res.data || []),
      error: () => this.errorMessage.set('Could not load tables - is backend-core running?'),
      complete: () => this.isLoadingTables.set(false)
    });
  }

  protected selectTable(table: string) {
    this.selectedTable.set(table);
    this.formData.set({});
    this.editingPkValue.set(null);
    this.errorMessage.set('');

    this.isLoadingColumns.set(true);
    this.adminService.getColumns(table).subscribe({
      next: (res) => this.columns.set(res.data || []),
      complete: () => this.isLoadingColumns.set(false)
    });
    this.loadRows();
  }

  private loadRows() {
    if (!this.selectedTable()) return;
    this.isLoadingRows.set(true);
    this.adminService.getRows(this.selectedTable()).subscribe({
      next: (res) => this.rows.set(res.data || []),
      error: () => this.errorMessage.set('Could not load rows'),
      complete: () => this.isLoadingRows.set(false)
    });
  }

  protected updateField(column: string, value: string) {
    this.formData.update((data) => ({ ...data, [column]: value }));
  }

  protected isAutoGenerated(column: ColumnInfo): boolean {
    const name = column.name.toLowerCase();
    return (
      column.primary_key ||
      name.includes('id') ||
      name.includes('embedding') ||
      name.includes('created_at') ||
      name.includes('updated_at') ||
      column.type.includes('vector')
    );
  }

  protected shouldShowInForm(column: ColumnInfo, isEditing: boolean): boolean {
    if (isEditing) return true;
    return !this.isAutoGenerated(column);
  }

  protected getColumnHint(column: ColumnInfo): string {
    const name = column.name.toLowerCase();
    if (column.primary_key || name.includes('id')) return '(auto-generated)';
    if (name.includes('embedding') || column.type.includes('vector')) return '(auto-generated)';
    if (name.includes('created_at')) return '(current time)';
    if (name.includes('updated_at')) return '(current time)';
    return '';
  }

  protected isJsonb(column: ColumnInfo): boolean {
    return column.type.toLowerCase().includes('jsonb');
  }

  protected isTimestamp(column: ColumnInfo): boolean {
    const type = column.type.toLowerCase();
    return type.includes('timestamp') || type.includes('datetime') || type.includes('date');
  }

  protected getJsonbPlaceholder(column: ColumnInfo): string {
    const name = column.name.toLowerCase();
    if (name.includes('config') || name.includes('settings')) {
      return '{"key": "value"}';
    }
    if (name.includes('data') || name.includes('metadata')) {
      return '{"field": "value"}';
    }
    return '{}';
  }

  protected startEdit(row: any) {
    const pkColumn = this.pkColumn();
    if (!pkColumn) return;

    const data: Record<string, string> = {};
    for (const key of this.rowColumns(row)) {
      data[key] = row[key] === null || row[key] === undefined ? '' : String(row[key]);
    }
    this.formData.set(data);
    this.editingPkValue.set(row[pkColumn]);
    this.errorMessage.set('');
  }

  protected cancelEdit() {
    this.formData.set({});
    this.editingPkValue.set(null);
    this.errorMessage.set('');
  }

  protected submit() {
    this.errorMessage.set('');
    this.isSubmitting.set(true);
    const data = this.formData();
    const convertedData = this.convertFormData(data);
    const editingPk = this.editingPkValue();
    const pkColumn = this.pkColumn();

    if (editingPk !== null && pkColumn) {
      this.adminService.updateRow(this.selectedTable(), pkColumn, editingPk, convertedData).subscribe({
        next: () => {
          this.cancelEdit();
          this.loadRows();
        },
        error: (err) => this.errorMessage.set(err?.error?.detail || 'Update failed'),
        complete: () => this.isSubmitting.set(false)
      });
      return;
    }

    const cleaned: Record<string, any> = {};
    for (const key in convertedData) {
      if (convertedData[key] !== '' && convertedData[key] !== null) {
        cleaned[key] = convertedData[key];
      }
    }

    this.adminService.insertRow(this.selectedTable(), cleaned).subscribe({
      next: () => {
        this.formData.set({});
        this.loadRows();
      },
      error: (err) => this.errorMessage.set(err?.error?.detail || 'Insert failed'),
      complete: () => this.isSubmitting.set(false)
    });
  }

  private convertFormData(data: Record<string, string>): Record<string, any> {
    const converted: Record<string, any> = {};
    const columnsMap = new Map(this.columns().map(c => [c.name, c]));

    for (const key in data) {
      const column = columnsMap.get(key);
      let value: any = data[key];

      if (column && value !== '') {
        const type = column.type.toLowerCase();

        if (type.includes('boolean')) {
          value = value === 'true' || value === true;
        } else if (type.includes('int') || type.includes('numeric') || type.includes('float')) {
          value = value === '' ? null : Number(value);
        }
      }

      converted[key] = value;
    }

    return converted;
  }

  protected deleteRow(row: any) {
    const pkColumn = this.pkColumn();
    if (!pkColumn) return;

    this.isSubmitting.set(true);
    this.adminService.deleteRow(this.selectedTable(), pkColumn, row[pkColumn]).subscribe({
      next: () => this.loadRows(),
      error: () => this.errorMessage.set('Delete failed'),
      complete: () => this.isSubmitting.set(false)
    });
  }

  protected rowColumns(row: any): string[] {
    return Object.keys(row);
  }

  protected refreshTable() {
    this.adminService.clearCache(this.selectedTable());
    this.loadRows();
  }

  protected openJsonEditor(fieldName: string) {
    this.jsonEditorField.set(fieldName);
    this.jsonEditorValue = this.formData()[fieldName] || '';
    this.jsonEditorOpen.set(true);
  }

  protected closeJsonEditor() {
    this.jsonEditorOpen.set(false);
    this.jsonEditorValue = '';
    this.jsonEditorField.set('');
  }

  protected saveJsonEditor() {
    const fieldName = this.jsonEditorField();
    this.updateField(fieldName, this.jsonEditorValue);
    this.closeJsonEditor();
  }
}

<div class="dashboard">
  <aside class="sidebar">
    <h2>Tables</h2>
    @if (isLoadingTables()) {
      <div class="loading-overlay">
        <span class="spinner"></span>
      </div>
    } @else {
      @for (table of tables(); track table) {
        <button class="table-btn" [class.active]="table === selectedTable()" (click)="selectTable(table)">
          {{ table }}
        </button>
      }
    }
  </aside>

  <main class="content">
    @if (errorMessage()) {
      <div class="error">{{ errorMessage() }}</div>
    }

    @if (!selectedTable()) {
      <div class="empty">Select a table to view and insert data.</div>
    }

    @if (selectedTable()) {
      <div>
        <div style="display: flex; align-items: center; gap: 12px; margin-bottom: 16px;">
          <h2 style="margin: 0;">{{ selectedTable() }}</h2>
          <button type="button" class="btn-refresh" (click)="refreshTable()">Refresh</button>
        </div>

        <form class="insert-form" (ngSubmit)="submit()" [class.loading]="isLoadingColumns() || isSubmitting()">
          @if (isLoadingColumns()) {
            <div class="form-loading">
              <span class="spinner"></span>
              <span>Loading fields...</span>
            </div>
          } @else {
            @for (col of columns(); track col.name) {
              @if (shouldShowInForm(col, editingPkValue() !== null)) {
                <div class="field" [class.auto-gen]="isAutoGenerated(col) && editingPkValue() === null">
                  <label>
                    {{ col.name }}
                    <span class="type">{{ col.type }}</span>
                    @if (getColumnHint(col)) {
                      <span class="hint">{{ getColumnHint(col) }}</span>
                    }
                    @if (col.primary_key) {
                      <span class="pk">PK</span>
                    }
                  </label>

                  @if (isJsonb(col)) {
                    <div class="jsonb-input-group">
                      <input
                        type="text"
                        [value]="(formData()[col.name] || '').substring(0, 50) + (formData()[col.name]?.length > 50 ? '...' : '')"
                        readonly
                        placeholder="{{ getJsonbPlaceholder(col) }}"
                        class="jsonb-preview"
                      />
                      <button
                        type="button"
                        class="btn-edit-json"
                        (click)="openJsonEditor(col.name)"
                        title="Edit JSON"
                      >
                        ✎
                      </button>
                    </div>
                  } @else if (isTimestamp(col)) {
                    <input
                      type="datetime-local"
                      [ngModel]="formData()[col.name] || ''"
                      (ngModelChange)="updateField(col.name, $event)"
                      [disabled]="editingPkValue() !== null && col.primary_key"
                      [readonly]="isAutoGenerated(col) && editingPkValue() === null"
                      name="{{ col.name }}"
                    />
                  } @else {
                    <input
                      type="text"
                      [ngModel]="formData()[col.name] || ''"
                      (ngModelChange)="updateField(col.name, $event)"
                      [disabled]="editingPkValue() !== null && col.primary_key"
                      [readonly]="isAutoGenerated(col) && editingPkValue() === null"
                      name="{{ col.name }}"
                      placeholder="{{ isAutoGenerated(col) ? 'Auto-generated' : '' }}"
                    />
                  }
                </div>
              }
            }
            <button type="submit" class="btn-insert" [disabled]="isLoadingColumns() || isSubmitting()">
              @if (isSubmitting()) {
                <span class="spinner small"></span>
                {{ editingPkValue() !== null ? 'Saving...' : 'Inserting...' }}
              } @else {
                {{ editingPkValue() !== null ? 'Save Changes' : 'Insert Row' }}
              }
            </button>
            @if (editingPkValue() !== null) {
              <button type="button" class="btn-cancel" (click)="cancelEdit()">Cancel</button>
            }
          }
        </form>

        <!-- JSON Editor Modal -->
        @if (jsonEditorOpen()) {
          <div class="modal-overlay" (click)="closeJsonEditor()">
            <div class="modal-content" (click)="$event.stopPropagation()">
              <div class="modal-header">
                <h3>Edit {{ jsonEditorField() }}</h3>
                <button type="button" class="btn-close" (click)="closeJsonEditor()">✕</button>
              </div>
              <textarea
                class="json-editor"
                [(ngModel)]="jsonEditorValue"
                placeholder='{"key": "value"}'
              ></textarea>
              <div class="modal-footer">
                <button type="button" class="btn-cancel" (click)="closeJsonEditor()">Cancel</button>
                <button type="button" class="btn-save-json" (click)="saveJsonEditor()">Save</button>
              </div>
            </div>
          </div>
        }

        @if (isLoadingRows()) {
          <div class="table-scroll">
            <table class="rows-table">
              <thead>
                <tr>
                  @for (col of columns(); track col.name) {
                    <th>{{ col.name }}</th>
                  }
                  <th></th>
                </tr>
              </thead>
              <tbody>
                @for (i of [0, 1, 2, 3, 4, 5]; track i) {
                  <tr class="skeleton-row">
                    @for (col of columns(); track col.name) {
                      <td><div class="skeleton-cell"></div></td>
                    }
                    <td><div class="skeleton-actions"></div></td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        } @else if (rows().length > 0) {
          <div class="table-scroll">
            <table class="rows-table">
              <thead>
                <tr>
                  @for (key of rowColumns(rows()[0]); track key) {
                    <th>{{ key }}</th>
                  }
                  <th></th>
                </tr>
              </thead>
              <tbody>
                @for (row of rows(); track (pkColumn() ? row[pkColumn()!] : $index)) {
                  <tr>
                    @for (key of rowColumns(row); track key) {
                      <td><div class="cell">{{ row[key] }}</div></td>
                    }
                    <td class="row-actions">
                      <button class="btn-edit" (click)="startEdit(row)">Edit</button>
                      <button class="btn-delete" (click)="deleteRow(row)">Delete</button>
                    </td>
                  </tr>
                }
              </tbody>
            </table>
          </div>
        }

        @if (rows().length === 0) {
          <div class="empty">No rows yet.</div>
        }
      </div>
    }
  </main>
</div>
